# Generated by Django 6.0.7 on 2026-07-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagemArtigo',
            new_name='ImageArticle',
        ),
    ]
