# Generated by Django 6.0.7 on 2026-07-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_imagemartigo_imagearticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
