# Generated by Django 6.0.7 on 2026-07-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_autor_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageArticle',
            new_name='ArticleImage',
        ),
    ]
