# Generated by Django 6.0.7 on 2026-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_imagearticle_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagem_capa',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='imagem',
            field=models.ImageField(upload_to='media/galeria/'),
        ),
    ]
