# Generated by Django 6.0.7 on 2026-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_imagem_capa_alter_articleimage_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagem_capa',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
