# Generated by Django 6.0.7 on 2026-07-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_imagem_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-data']},
        ),
    ]
