# Generated by Django 6.0.7 on 2026-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagem_capa',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
