# Generated by Django 6.0.7 on 2026-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
