# Generated by Django 6.0.7 on 2026-08-05 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.category'),
        ),
    ]
