# Generated by Django 6.0.7 on 2026-08-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_autor_alter_article_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='conteudo',
        ),
    ]
