# Generated by Django 6.0.7 on 2026-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conteudo',
            field=models.TextField(default=''),
        ),
    ]
