# Generated by Django 6.0.7 on 2026-08-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='conteudo',
        ),
    ]
