# Generated by Django 6.0.7 on 2026-08-31 18:14

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_article_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conteudo',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
