# Generated by Django 6.0.7 on 2026-09-22 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de primeira publicação'),
        ),
    ]
