# Generated by Django 6.0.7 on 2026-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_data_publicacao_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de primeira publicação'),
        ),
    ]
